<?php

/**
 * Automatic URL replacement engine.
 *
 * Converts wp-content/uploads/… URLs to custom path URLs everywhere on the
 * front end — including inside <picture> / <source srcset="…"> tags built
 * by layoutkit_render_picture_tag_v2() and similar theme functions that
 * construct WebP URLs via string manipulation instead of WP filters.
 *
 * APPROACH:
 *  Layer 1 — WordPress filters (replaces at the PHP data level, before HTML):
 *    wp_get_attachment_url, wp_get_attachment_image_src,
 *    wp_calculate_image_srcset, wp_get_attachment_image_attributes,
 *    the_content, acf/format_value/type=image, acf/format_value/type=file
 *
 *  Layer 2 — Output buffer (catches anything Layer 1 misses, e.g. manually
 *    constructed <picture> tags, hardcoded HTML, widget output):
 *    ob_start() + strtr() over the full HTML with a pre-built lookup map.
 *
 * WebP companion entries are PRE-POPULATED into the map so the buffer's
 * strtr() can replace WebP URLs generated by:
 *   preg_replace('/\.png$/i', '.webp', $desk_url)
 * inside layoutkit_render_picture_tag_v2() — those URLs bypass all WP filters.
 *
 * @package WP_Media_Manager
 */

namespace WP_Media_Manager;

if (! defined('ABSPATH')) {
	exit;
}

/**
 * Class Url_Replacer
 */
class Url_Replacer
{

	/** @var Database */
	private Database $db;

	/**
	 * Cached lookup map: decoded_original_url → custom_url.
	 * null = not yet built. Built once per request.
	 *
	 * @var array<string,string>|null
	 */
	private static ?array $map = null;

	/**
	 * @param Database $db
	 */
	public function __construct(Database $db)
	{
		$this->db = $db;
	}

	/**
	 * Register hooks. Called unconditionally from Plugin — internal guards
	 * prevent this running on admin/AJAX/REST/CLI requests.
	 *
	 * @return void
	 */
	public function register(): void
	{
		if (is_admin()) {
			return;
		}

		// Layer 1 — WP filters
		add_filter('wp_get_attachment_url',                [$this, 'filter_url'], 20);
		add_filter('wp_get_attachment_image_src',          [$this, 'filter_image_src'], 20);
		add_filter('wp_calculate_image_srcset',            [$this, 'filter_srcset'], 20);
		add_filter('wp_get_attachment_image_attributes',   [$this, 'filter_img_attrs'], 20, 2);
		add_filter('the_content',                          [$this, 'filter_content'], 20);
		add_filter('acf/format_value/type=image',          [$this, 'filter_acf_image'], 20, 3);
		add_filter('acf/format_value/type=file',           [$this, 'filter_acf_file'], 20, 3);

		// Layer 2
		add_action('template_redirect', [$this, 'start_buffer'], 1);
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Layer 2 — Output buffer
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Start output buffering on front-end page requests.
	 *
	 * @return void
	 */
	public function start_buffer(): void
	{
		if ($this->should_skip()) {
			return;
		}

		ob_start([$this, 'process_buffer']);
	}

	/**
	 * Process the complete HTML output and replace all upload URLs.
	 *
	 * OPTIMIZED: Instead of running strtr() over the entire HTML with a massive 
	 * 50,000-item map (which causes Memory Exhaustion), we extract only the 
	 * actual upload URLs present in this specific HTML using Regex. 
	 * Since Layer 1 filters already replaced 95% of URLs, Layer 2 will only 
	 * find a handful of hardcoded URLs (e.g., 5-10 WebP URLs from theme's <picture> tag).
	 *
	 * @param string $html
	 * @return string
	 */
	public function process_buffer(string $html): string
	{
		if (empty($html)) {
			return $html;
		}

		$map = $this->get_map();

		if (empty($map)) {
			return $html;
		}

		// 1. Find ONLY the upload URLs that actually exist in this HTML.
		$upload_base = $this->get_upload_base_url();
		$escaped_base = preg_quote($upload_base, '/');

		// Matches https://site.com/wp-content/uploads/... 
		preg_match_all('/(?:https?:)?\/\/[^ "\'>]*?' . $escaped_base . '[^ "\'>]+/i', $html, $matches);

		$found_urls = array_unique($matches[0]);

		if (empty($found_urls)) {
			return $html;
		}

		// 2. Build a MICRO map containing ONLY the URLs found in this HTML.
		$replacements = [];
		foreach ($found_urls as $raw_url) {
			$clean = rawurldecode(strtok($raw_url, '?'));

			// Check our master map
			if (isset($map[$clean])) {
				$replacements[$raw_url] = $map[$clean];
			} elseif (isset($map[$raw_url])) {
				$replacements[$raw_url] = $map[$raw_url];
			}
		}

		// 3. Replace using the tiny micro map (blazing fast, zero memory issues).
		if (!empty($replacements)) {
			$html = strtr($html, $replacements);
		}

		// 4. Handle data-attributes (srcsets inside custom data fields)
		$html = preg_replace_callback(
			'/(data-[a-zA-Z0-9\-]+=["\'])([^"\']+)(["\'])/',
			function ($matches) use ($map) {
				$attribute_prefix = $matches[1];
				$attribute_value  = $matches[2];

				$clean_url = rawurldecode(strtok($attribute_value, '?'));
				if (isset($map[$clean_url])) {
					return $attribute_prefix . $map[$clean_url];
				}

				if (str_contains($attribute_value, ',')) {
					$candidates = explode(',', $attribute_value);
					foreach ($candidates as &$candidate) {
						$parts = preg_split('/\s+/', trim($candidate));
						if (! empty($parts[0])) {
							$cand_clean = rawurldecode(strtok($parts[0], '?'));
							if (isset($map[$cand_clean])) {
								$parts[0] = $map[$cand_clean];
							}
						}
						$candidate = implode(' ', (array) $parts);
					}
					unset($candidate);
					return $attribute_prefix . implode(', ', $candidates);
				}

				return $matches[0];
			},
			$html
		);

		return $html;
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Layer 1 — WordPress filters
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Filter wp_get_attachment_url().
	 *
	 * @param string $url
	 * @return string
	 */
	public function filter_url(string $url): string
	{
		return $this->replace_url($url) ?? $url;
	}

	/**
	 * Filter wp_get_attachment_image_src() → [url, w, h, resized].
	 *
	 * @param array<mixed>|false $image
	 * @return array<mixed>|false
	 */
	public function filter_image_src($image)
	{
		if (! is_array($image) || empty($image[0])) {
			return $image;
		}
		$replaced = $this->replace_url((string) $image[0]);
		if ($replaced) {
			$image[0] = $replaced;
		}
		return $image;
	}

	/**
	 * Filter wp_calculate_image_srcset() — array of srcset candidates.
	 *
	 * @param array<int,array<string,mixed>> $sources
	 * @return array<int,array<string,mixed>>
	 */
	public function filter_srcset(array $sources): array
	{
		foreach ($sources as &$source) {
			if (! empty($source['url'])) {
				$replaced = $this->replace_url((string) $source['url']);
				if ($replaced) {
					$source['url'] = $replaced;
				}
			}
		}
		unset($source);
		return $sources;
	}

	/**
	 * Filter the_content() — replaces upload URLs in post body HTML.
	 *
	 * @param string $content
	 * @return string
	 */
	public function filter_content(string $content): string
	{
		$map = $this->get_map();
		if (empty($map)) {
			return $content;
		}
		return strtr($content, $map);
	}

	/**
	 * Filter wp_get_attachment_image_attributes().
	 *
	 * @param array<string,string> $attr
	 * @param \WP_Post             $attachment
	 * @return array<string,string>
	 */
	public function filter_img_attrs(array $attr, \WP_Post $attachment): array
	{
		if (! empty($attr['src'])) {
			$replaced = $this->replace_url($attr['src']);
			if ($replaced) {
				$attr['src'] = $replaced;
			}
		}
		if (! empty($attr['srcset'])) {
			$attr['srcset'] = $this->replace_srcset_string($attr['srcset']);
		}
		return $attr;
	}

	/**
	 * Filter ACF image fields.
	 *
	 * NOTE: $post_id is intentionally untyped. ACF passes it as a mixed value:
	 * an int for regular posts, or a string like "option", "block_abc123",
	 * "widget_N" in other contexts. Adding `int` here causes a TypeError.
	 *
	 * @param mixed        $value
	 * @param int|string   $post_id  ACF context — int OR string, never type-hint this.
	 * @param array<mixed> $field
	 * @return mixed
	 */
	public function filter_acf_image($value, $post_id, $field)
	{
		if (is_array($value)) {
			return $this->replace_urls_in_array($value);
		}
		if (is_string($value) && ! empty($value)) {
			return $this->replace_url($value) ?? $value;
		}
		return $value;
	}

	/**
	 * Filter ACF file fields (PDFs, downloads).
	 *
	 * @param mixed        $value
	 * @param int|string   $post_id  — see filter_acf_image() note above.
	 * @param array<mixed> $field
	 * @return mixed
	 */
	public function filter_acf_file($value, $post_id, $field)
	{
		return $this->filter_acf_image($value, $post_id, $field);
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Public helper (for theme / plugin code)
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Convert any WordPress upload URL to its custom path URL.
	 *
	 * Returns the original URL if no mapping exists.
	 * Handles WebP variants automatically via the pre-built map.
	 *
	 *   echo wpmm_custom_url( $image_array['url'] );
	 *   $webp = wpmm_custom_url( $image_array['url_webp'] );
	 *
	 * @param string $url
	 * @return string
	 */
	public function get_custom_url(string $url): string
	{
		return $this->replace_url($url) ?? $url;
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Core replacement logic
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Replace a single URL if a mapping exists.
	 *
	 * @param string $url
	 * @return string|null Replaced URL or null if no mapping.
	 */
	private function replace_url(string $url): ?string
	{
		if (empty($url)) {
			return null;
		}

		$clean = rawurldecode(strtok($url, '?'));
		$map   = $this->get_map();

		// Direct hit (original or WebP companion key).
		if (isset($map[$clean])) {
			return $map[$clean];
		}

		// Try the URL as-is (in case it was stored percent-encoded).
		if (isset($map[$url])) {
			return $map[$url];
		}

		return null;
	}

	/**
	 * Replace all upload URLs in a srcset attribute string.
	 *
	 * Format: "url1 1x, url2 800w"
	 *
	 * @param string $srcset
	 * @return string
	 */
	private function replace_srcset_string(string $srcset): string
	{
		$candidates = explode(',', $srcset);

		foreach ($candidates as &$candidate) {
			$parts = preg_split('/\s+/', trim($candidate));
			if (! empty($parts[0])) {
				$replaced = $this->replace_url($parts[0]);
				if ($replaced) {
					$parts[0] = $replaced;
				}
			}
			$candidate = implode(' ', (array) $parts);
		}
		unset($candidate);

		return implode(', ', $candidates);
	}

	/**
	 * Recursively replace upload URLs in an array (for ACF image/file arrays).
	 *
	 * @param array<mixed> $data
	 * @return array<mixed>
	 */
	private function replace_urls_in_array(array $data): array
	{
		$upload_base = $this->get_upload_base_url();

		array_walk_recursive($data, function (&$value) use ($upload_base): void {
			if (
				is_string($value)
				&& str_starts_with(rawurldecode(strtok($value, '?')), $upload_base)
			) {
				$replaced = $this->replace_url($value);
				if ($replaced) {
					$value = $replaced;
				}
			}
		});

		return $data;
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Lookup map
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Build and return the original_url → custom_url lookup map.
	 *
	 * Built once per request (statically cached).
	 *
	 * Map keys for each entry:
	 *  1. Stored original_url (decoded)      — the URL at time of save.
	 *  2. Live wp_get_attachment_url()        — current URL after file replacement.
	 *     This is what makes attachment-replacement transparent: if the file
	 *     was moved from /2026/04/home.png to /2026/05/home.png, WordPress
	 *     outputs the new URL. Our map needs both old and new as keys so
	 *     the custom URL (/image/home.png) is substituted correctly in both
	 *     old and new HTML output.
	 *  3. Stored original_url (encoded)       — percent-encoded variant.
	 *  4. WebP companion URL (decoded)        — for layoutkit_render_picture_tag().
	 *
	 * @return array<string,string>
	 */
	private function get_map(): array
	{
		if (null !== self::$map) {
			return self::$map;
		}

		$cached_map = get_transient('wpmm_url_lookup_map');
		if (is_array($cached_map)) {
			self::$map = $cached_map;
			return self::$map;
		}

		self::$map = [];

		$entries = $this->db->get_all(['per_page' => -1, 'page' => 1]);

		if (empty($entries)) {
			return self::$map;
		}

		foreach ($entries as $entry) {
			$custom = $this->build_custom_url($entry);
			if (! $custom) {
				continue;
			}

			// ── Key set A: stored original_url ───────────────────────────────
			$original_raw = (string) $entry->original_url;
			$original     = rawurldecode(strtok($original_raw, '?'));

			if (! empty($original)) {
				self::$map[$original] = $custom;

				// Also add encoded variant.
				if ($original_raw !== $original) {
					self::$map[$original_raw] = $custom;
				}

				// WebP companion for the stored URL.
				$this->add_webp_companion($original, $custom);
			}

			// ── Key set B: live attachment URL ────────────────────────────────
			// wp_get_attachment_url() reflects the CURRENT location of the file.
			// After a file replacement (new month/year folder), this differs from
			// original_url. We add it as an additional key so the map always
			// intercepts whatever URL WordPress is currently outputting.
			if ($entry->attachment_id) {
				$live_url = wp_get_attachment_url((int) $entry->attachment_id);

				if ($live_url) {
					$live_clean = rawurldecode(strtok($live_url, '?'));

					// Only add if it's a new key (avoids redundant work when
					// the attachment hasn't been replaced).
					if ($live_clean !== $original && ! empty($live_clean)) {
						self::$map[$live_clean] = $custom;

						// WebP companion for the live URL.
						$this->add_webp_companion($live_clean, $custom);
					}
				}
			}
		}
		set_transient('wpmm_url_lookup_map', self::$map, 24 * HOUR_IN_SECONDS);

		return self::$map;
	}

	/**
	 * Add WebP companion entries to the map for one source URL → custom URL pair.
	 *
	 * Given:
	 *   source    = https://…/uploads/2026/04/lesion-progression.png
	 *   custom    = https://example.com/image/lesion-progression.png
	 *
	 * Adds:
	 *   https://…/uploads/2026/04/lesion-progression.webp
	 *   → https://example.com/image/lesion-progression.webp
	 *
	 * This is exactly what layoutkit_render_picture_tag_v2() computes:
	 *   $desk_webp = preg_replace('/\.png$/i', '.webp', $desk_url);
	 *
	 * @param string $source_url    Decoded original upload URL.
	 * @param string $source_custom Full custom URL already in the map.
	 * @return void
	 */
	private function add_webp_companion(string $source_url, string $source_custom): void
	{
		$ext = strtolower(pathinfo($source_url, PATHINFO_EXTENSION));

		// Only derive companions for image types that get WebP-converted.
		if (! in_array($ext, ['jpg', 'jpeg', 'png', 'gif'], true)) {
			return;
		}

		// Build the WebP upload URL.
		$webp_upload = (string) preg_replace(
			'/\.' . preg_quote($ext, '/') . '$/i',
			'.webp',
			$source_url
		);

		if (! $webp_upload || $webp_upload === $source_url) {
			return;
		}

		// Build the WebP custom URL.
		$custom_ext = strtolower(pathinfo($source_custom, PATHINFO_EXTENSION));

		if ($custom_ext === $ext) {
			// Custom URL ends in source ext → swap to .webp.
			$webp_custom = (string) preg_replace(
				'/\.' . preg_quote($ext, '/') . '$/i',
				'.webp',
				$source_custom
			);
		} elseif ($custom_ext === 'webp') {
			$webp_custom = $source_custom; // Already .webp — no-op.
		} else {
			// No extension in custom URL → append .webp.
			$webp_custom = rtrim($source_custom, '/') . '.webp';
		}

		if ($webp_custom && $webp_custom !== $source_custom) {
			self::$map[$webp_upload] = $webp_custom;
		}
	}

	/**
	 * Build the full public custom URL for a DB entry.
	 *
	 * Uses the live attachment URL (not the stored original_url) as the
	 * source for the file extension — so that if the attachment was replaced,
	 * the extension in the custom URL is always correct.
	 *
	 * @param object $entry
	 * @return string|null
	 */
	private function build_custom_url(object $entry): ?string
	{
		// Prefer live URL for extension resolution.
		$source_url = (string) $entry->original_url;
		if ($entry->attachment_id) {
			$live = wp_get_attachment_url((int) $entry->attachment_id);
			if ($live) {
				$source_url = $live;
			}
		}

		$output_path = Helper::build_output_path(
			$entry->custom_name,
			$entry->custom_path,
			(bool) $entry->include_extension,
			$source_url
		);

		if (empty($output_path)) {
			return null;
		}

		// Encode each path segment individually so spaces → %20, slashes stay.
		$segments = array_map('rawurlencode', explode('/', $output_path));
		return home_url('/' . implode('/', $segments));
	}

	/**
	 * Get the uploads base URL (cached per request).
	 *
	 * @return string  e.g. https://example.com/wp-content/uploads/
	 */
	private function get_upload_base_url(): string
	{
		static $base = null;
		if (null === $base) {
			$base = trailingslashit(wp_upload_dir()['baseurl']);
		}
		return $base;
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Guard
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Should we skip URL replacement for this request?
	 *
	 * Skip admin, AJAX, REST API, cron, CLI — only run for regular front-end
	 * HTML page responses.
	 *
	 * @return bool True = skip.
	 */
	private function should_skip(): bool
	{

		if (is_admin()) {
			return true;
		}
		if (defined('REST_REQUEST') && REST_REQUEST) {
			return true;
		}
		if (defined('DOING_CRON') && DOING_CRON) {
			return true;
		}

		if (isset($_REQUEST['action'])) {
			$action = sanitize_text_field(wp_unslash($_REQUEST['action']));
			if (str_contains($action, 'query-attachments') || str_contains($action, 'save-attachment')) {
				return true;
			}
		}
		return false;
	}
}
